/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NeighbouringFileNavigatorPlugin
});
module.exports = __toCommonJS(main_exports);

// src/NeighbouringFileNavigator.ts
var import_obsidian = require("obsidian");
var _NeighbouringFileNavigator = class {
  static reverse(fn) {
    return (a, b) => -fn(a, b);
  }
  static getFileExplorerSortOrder(workspace, settings) {
    var _a, _b, _c, _d, _e;
    return (_e = (_d = (_c = (_b = (_a = workspace.getLeavesOfType("file-explorer")) == null ? void 0 : _a.first()) == null ? void 0 : _b.getViewState()) == null ? void 0 : _c.state) == null ? void 0 : _d.sortOrder) != null ? _e : settings.defaultSortOrder;
  }
  static navigateToNextFile(workspace, settings) {
    const sortOrder = this.getFileExplorerSortOrder(workspace, settings);
    console.debug("navigateToNextFile with sortOrder", sortOrder);
    const sortFn = this.sorters[sortOrder];
    this.navigateToNeighbouringFile(workspace, sortFn);
  }
  static navigateToPrevFile(workspace, settings) {
    const sortOrder = this.getFileExplorerSortOrder(workspace, settings);
    console.debug("navigateToPrevFile with sortOrder", sortOrder);
    const sortFn = this.sorters[sortOrder];
    this.navigateToNeighbouringFile(workspace, this.reverse(sortFn));
  }
  static navigateToNextAlphabeticalFile(workspace) {
    console.debug("navigateToNextAlphabeticalFile");
    this.navigateToNeighbouringFile(workspace, this.sorters.alphabetical);
  }
  static navigateToPrevAlphabeticalFile(workspace) {
    console.debug("navigateToPrevAlphabeticalFile");
    this.navigateToNeighbouringFile(workspace, this.sorters.alphabeticalReverse);
  }
  static navigateToOlderCreatedFile(workspace) {
    console.debug("navigateToOlderCreatedFile");
    this.navigateToNeighbouringFile(workspace, this.sorters.byCreatedTime);
  }
  static navigateToNewerCreatedFile(workspace) {
    console.debug("navigateToNewerCreatedFile");
    this.navigateToNeighbouringFile(workspace, this.sorters.byCreatedTimeReverse);
  }
  static navigateToOlderModifiedFile(workspace) {
    console.debug("navigateToOlderModifiedFile");
    this.navigateToNeighbouringFile(workspace, this.sorters.byModifiedTime);
  }
  static navigateToNewerModifiedFile(workspace) {
    console.debug("navigateToNewerModifiedFile");
    this.navigateToNeighbouringFile(workspace, this.sorters.byModifiedTimeReverse);
  }
  static navigateToNeighbouringFile(workspace, sortFn) {
    const activeFile = workspace.getActiveFile();
    if (!activeFile)
      return;
    const files = this.getNeighbouringFiles(activeFile, sortFn);
    if (!files)
      return;
    const currentItem = files.findIndex(
      (item) => item.name === activeFile.name
    );
    const toFile = files[(currentItem + 1) % files.length];
    workspace.getLeaf(false).openFile(toFile);
  }
  static getNeighbouringFiles(file, sortFn) {
    var _a;
    const files = (_a = file == null ? void 0 : file.parent) == null ? void 0 : _a.children;
    const filteredFiles = files == null ? void 0 : files.filter((f) => f instanceof import_obsidian.TFile && f.extension === "md");
    const sortedFiles = filteredFiles == null ? void 0 : filteredFiles.sort(sortFn);
    return sortedFiles;
  }
};
var NeighbouringFileNavigator = _NeighbouringFileNavigator;
NeighbouringFileNavigator.localeSorter = (a, b) => a.basename.localeCompare(
  b.basename,
  void 0,
  { numeric: true, sensitivity: "base" }
);
NeighbouringFileNavigator.mtimeSorter = (a, b) => {
  return b.stat.mtime - a.stat.mtime;
};
NeighbouringFileNavigator.ctimeSorter = (a, b) => {
  return b.stat.ctime - a.stat.ctime;
};
NeighbouringFileNavigator.sorters = {
  alphabetical: _NeighbouringFileNavigator.localeSorter,
  byCreatedTime: _NeighbouringFileNavigator.ctimeSorter,
  byModifiedTime: _NeighbouringFileNavigator.mtimeSorter,
  alphabeticalReverse: _NeighbouringFileNavigator.reverse(_NeighbouringFileNavigator.localeSorter),
  byCreatedTimeReverse: _NeighbouringFileNavigator.reverse(_NeighbouringFileNavigator.ctimeSorter),
  byModifiedTimeReverse: _NeighbouringFileNavigator.reverse(_NeighbouringFileNavigator.mtimeSorter)
};

// src/NeighbouringFileNavigatorPluginSettingTab.ts
var import_obsidian2 = require("obsidian");
var NeighbouringFileNavigatorPluginSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    let { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Default Sort Order").setDesc("Fallback sort order used for the default command").addDropdown((dropdown) => {
      dropdown.addOption("alphabetical", "Alphabetical");
      dropdown.addOption("byCreatedTime", "Creation Timestamp");
      dropdown.addOption("byModifiedTime", "Modification Timestamp");
      dropdown.setValue(this.plugin.settings.defaultSortOrder);
      dropdown.onChange(async (value) => {
        this.plugin.settings.defaultSortOrder = value;
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/main.ts
var import_obsidian3 = require("obsidian");
var DEFAULT_SETTINGS = {
  defaultSortOrder: "alphabetical"
};
var NeighbouringFileNavigatorPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new NeighbouringFileNavigatorPluginSettingTab(this.app, this));
    this.addCommand({
      id: "next",
      name: "Navigate to next file",
      callback: () => NeighbouringFileNavigator.navigateToNextFile(this.app.workspace, this.settings)
    });
    this.addCommand({
      id: "prev",
      name: "Navigate to prev file",
      callback: () => NeighbouringFileNavigator.navigateToPrevFile(this.app.workspace, this.settings)
    });
    this.addCommand({
      id: "next-alphabetical",
      name: "Navigate to next file (alphabetical)",
      callback: () => NeighbouringFileNavigator.navigateToNextAlphabeticalFile(this.app.workspace)
    });
    this.addCommand({
      id: "prev-alphabetical",
      name: "Navigate to prev file (alphabetical)",
      callback: () => NeighbouringFileNavigator.navigateToPrevAlphabeticalFile(this.app.workspace)
    });
    const olderCreatedCommand = {
      name: "Navigate to older file (creation timestamp)",
      callback: () => NeighbouringFileNavigator.navigateToOlderCreatedFile(this.app.workspace)
    };
    this.addCommand({ ...olderCreatedCommand, id: "older-created" });
    this.addCommand({ ...olderCreatedCommand, id: "prev-created" });
    const newerCreatedCommand = {
      name: "Navigate to newer file (creation timestamp)",
      callback: () => NeighbouringFileNavigator.navigateToNewerCreatedFile(this.app.workspace)
    };
    this.addCommand({ ...newerCreatedCommand, id: "next-created" });
    this.addCommand({ ...newerCreatedCommand, id: "newer-created" });
    const olderModifiedCommand = {
      name: "Navigate to older file (modification timestamp)",
      callback: () => NeighbouringFileNavigator.navigateToOlderModifiedFile(this.app.workspace)
    };
    this.addCommand({ ...olderModifiedCommand, id: "older-modified" });
    this.addCommand({ ...olderModifiedCommand, id: "prev-modified" });
    const newerModifiedCommand = {
      name: "Navigate to newer file (modification timestamp)",
      callback: () => NeighbouringFileNavigator.navigateToNewerModifiedFile(this.app.workspace)
    };
    this.addCommand({ ...newerModifiedCommand, id: "next-modified" });
    this.addCommand({ ...newerModifiedCommand, id: "newer-modified" });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};

/* nosourcemap */